CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  level INT DEFAULT 1,
  xp INT DEFAULT 0,
  hp INT DEFAULT 100,
  stats JSON,
  wallet_gold INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  reward_xp INT DEFAULT 10,
  reward_gold INT DEFAULT 5,
  type ENUM('DAILY', 'WEEKLY', 'MAIN', 'SIDE') DEFAULT 'DAILY',
  status ENUM('ACTIVE', 'COMPLETED', 'FAILED') DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
